/**
 * The soundtrack, as a list of cues against the film's own clock.
 *
 * Every file under `public/audio/` is generated by `scripts/make-audio.py` from
 * oscillators and noise — nothing is sampled or licensed, and the whole score can
 * be regenerated from source. The tune runs at 120bpm, so a bar is two seconds
 * and the music's phrases line up with the cut without drifting.
 *
 * Times below are seconds from the start of the film, and each one is the frame
 * its animation actually fires on, read off the scene that owns it. When a scene's
 * timing moves, its cue moves with it or the sound detaches from the picture.
 */
export type Sfx = "pop" | "stamp" | "ding" | "whoosh" | "tap" | "tick";

export type Cue = {
  at: number;
  sound: Sfx;
  /** Relative to the effect's own normalised level. */
  volume: number;
};

/** Spreads one sound across a staggered group, matching the stagger on screen. */
function stagger(start: number, step: number, count: number, sound: Sfx, volume: number): Cue[] {
  return Array.from({ length: count }, (_, i) => ({ at: start + i * step, sound, volume }));
}

export const CUES: readonly Cue[] = [
  // Hook — the mark lands.
  { at: 0.12, sound: "stamp", volume: 0.55 },

  // What it is — the balance lands on its rule.
  { at: 3.45, sound: "ding", volume: 0.4 },

  // Sending — four characters typed, the amount, the press, and the money.
  ...stagger(7.55, 0.075, 4, "tick", 0.3),
  { at: 8.35, sound: "pop", volume: 0.26 },
  { at: 9.4, sound: "tap", volume: 0.45 },
  { at: 9.75, sound: "ding", volume: 0.6 },

  // Who can move it — three promises arriving under their rules.
  ...stagger(12.45, 0.14, 3, "pop", 0.2),

  // Mini Apps, beat one — six tiles.
  ...stagger(15.3, 0.09, 6, "pop", 0.3),

  // Beat two — eight chips.
  ...stagger(17.9, 0.1, 8, "pop", 0.28),

  // Beat three — the sheet rises, the button goes down, the payment is approved.
  { at: 21.05, sound: "whoosh", volume: 0.42 },
  { at: 22.0, sound: "tap", volume: 0.45 },
  { at: 22.3, sound: "ding", volume: 0.55 },

  // Beat four — the install line is stamped, then the three claims.
  { at: 23.4, sound: "stamp", volume: 0.5 },
  ...stagger(23.95, 0.16, 3, "pop", 0.24),

  // Close — the mark again, then the address.
  { at: 26.08, sound: "stamp", volume: 0.5 },
  { at: 27.25, sound: "pop", volume: 0.3 },
];

/** The score sits under everything; the cues are what the eye is being pointed at. */
export const MUSIC_VOLUME = 0.3;
